Conf parsing v0.1
xGoldaxe/webserv pull request #18
Opened 2022-05-31 11:58 UTC by Vatar

Parser prototype able to output a parsed server & routes out of a specific syntax config file

test by executing ./webserv testconf

Need refinement, stricter parsing checks and extensions but the template is in a final state, just to add upon.

2022-05-31 12:36 UTC, restray requested changes
### Pour le fichier de configuration:

Il faudrait clarifier les instructions dans le fichier de config!
Pourquoi utiliser des "=", quand les utiliser, les differentes instructions existantes et les differents niveaux d'imbrication.

### Commit precedents

Tu as fait une mauvaise manip' !
Mets d'abord a jour ta branche:
 - Tu merge master dans ta branch
 - Ensuite tu check que tes comportements sont tjr les bons
 - Et apres tu peux refaire une pull request de ta branche dans master!

2022-05-31 12:36 UTC, restray commented on .gitignore
> -.nfs*
Pourquoi supprimer ce fichier?

2022-05-31 12:36 UTC, restray commented on .vscode/settings.json
> +}
Pense a supprimer ce fichier

2022-05-31 12:36 UTC, restray commented on Makefile
> -			init/exception_server_not_listening.cpp \
Pense a ajouter tes fichiers a la fin !

2022-05-31 12:36 UTC, restray commented on Makefile
> -			class/webserv_conf.cpp \
Obligatoire?

2022-05-31 12:36 UTC, restray commented on Makefile
> -CPPFLAGS	=	-Wall -Wextra -Werror -I. -std=c++98 -D DEBUG
Laisse le debug pour le temps du developpement

2022-05-31 12:36 UTC, restray commented on defaultPages/404.html
> +	<link rel="stylesheet" href="../404.css">
Cette syntaxe la n'est pas bonne...
Evitons les ".." dans les requetes HTTP par le serveur!

Au pire mettez le contenu du fichier CSS dans une balise `<style></style>`

2022-05-31 12:36 UTC, restray commented on todo
> +to change for multi-server support
Passe ca sur des issues GitHub plutot! Les TODO dans le code c'est pas le top ahah!

2022-05-31 12:51 UTC, Vatar commented on .gitignore
> -.nfs*
Je vois qu'il n'y avait pas de .gitignore quand j'ai branch la semaine dernière, il a été rajouté hier dans la branch master, je le récupèrerais avec le merge du coup

2022-05-31 13:02 UTC, xGoldaxe commented on Makefile
> -			class/webserv_conf.cpp \
non

2022-05-31 13:02 UTC, xGoldaxe commented on defaultPages/404.html
> +	<link rel="stylesheet" href="../404.css">
Comment ca? on est sense pouvoir supporter ce genre d'appelle

2022-05-31 13:03 UTC, xGoldaxe commented on todo
> +to change for multi-server support
en effet ahah

2022-05-31 13:47 UTC, Vatar commented on Makefile
> -CPPFLAGS	=	-Wall -Wextra -Werror -I. -std=c++98 -D DEBUG
Oki, corrigé avec le merge master

2022-05-31 13:48 UTC, Vatar commented on .vscode/settings.json
> +}
Oki, enlevé manuellement après le merge

2022-05-31 13:48 UTC, Vatar commented on .gitignore
> -.nfs*
Bien récupéré

2022-05-31 13:52 UTC, Vatar commented on todo
> +to change for multi-server support
Je rajoute les issues du coup, à peu près dans l'ordre:
1. Finir les fonctionalités essentielles du parser 
2. Implementer le parsing multi-serveur
^ je m'en occupe, puis:
3. Request ne prend que le 1er server actuellement, à modifier pour prendre en compte le Multi-serveur
4. Utiliser le parser et ce qui est renvoyé par celle-ci si on nous donne un fichier en argument

2022-05-31 14:14 UTC, Vatar commented on Makefile
> -			init/exception_server_not_listening.cpp \
aaaah, je me suis fait avoir avec le merge encore une fois, corrigé

2022-05-31 14:16 UTC, Vatar commented
> ### Pour le fichier de configuration:
> Il faudrait clarifier les instructions dans le fichier de config! Pourquoi utiliser des "=", quand les utiliser, les differentes instructions existantes et les differents niveaux d'imbrication.
> 
> ### Commit precedents
> Tu as fait une mauvaise manip' ! Mets d'abord a jour ta branche:
> 
> * Tu merge master dans ta branch
> * Ensuite tu check que tes comportements sont tjr les bons
> * Et apres tu peux refaire une pull request de ta branche dans master!

Excuse-moi, j'ai bien merge et corrigé derrière, merci beaucoup pour le review

Pour la syntaxe, les règles du parser est qu'il s'attend à

```
server
   x = y ;
   etc...
         location
               etc..
         location
               etc..
```
error_page a b ... z = xxx ;
methods = a b ... z ;
index = a b ... z ;
avec toujours une espace entre chaque mot
Je dois rajouter si plusieurs bloc server, si quelqu'un passe un bloc sever dans location...

2022-05-31 21:00 UTC, restray approved these changes
Tout est bon!

Pour les petits conseils que je pourrais te donner:
 - Tes définitions de fonctions n'ont pas à terminées par des ";"

Pour ta class `Route`:
 - As-tu besoin que toutes tes variables soient définies en public? ça peut créer des problèmes de compréhensions ici!
 - Pour le linting: pense à indenter/aligner correctement tes lignes :D

Globalement des erreurs de linting ou de la documentation manquante!
Sinon tout est bon ;)

2022-05-31 21:00 UTC, restray commented on srcs/class/request.hpp
> +#	define REQUEST_HPP
Utilise plutôt:

```suggestion
#pragma once
```

2022-05-31 21:00 UTC, restray commented on srcs/class/request.hpp
> +#endif
Et tu peux le virer ici ducoup !
```suggestion
```

2022-05-31 21:00 UTC, restray commented on srcs/class/response.cpp
> +	// std::cout << raw_response << std::endl;
Pour permettre l'affichage de cette info quand on utilise le mod debug!
```suggestion
	#ifdefine DEBUG
		std::cout << raw_response << std::endl;
	#endif
```

2022-05-31 21:00 UTC, restray commented on srcs/class/response.hpp
> +#	define RESPONSE_HPP
Même suggestion que pour l'autre header!
```suggestion
#pragma once
```

2022-05-31 21:00 UTC, restray commented on srcs/class/response.hpp
> +#endif
Et n'oublie pas de l'enlever ici!
```suggestion
```

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
>  	this->location = location;
*Tips*: 
 - Préfère préfixer les variables de ta class avec un underscore (`_location` et `_root`)

Et ici tu peux mettre set les valeurs directement dans la déclaration de la fonction!

```suggestion
Route::Route(std::string location, std::string root) : root(root), location(location)
{
```

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
> +	this->cgi_enable = false;
Tu peux utiliser les `auto_index` et `cgi_enabled` en tant qu'options (avec une valeur par défaut, donc facultatifs)! Et en plus tu pourras les ajouter dans les sets de valeurs :D

```suggestion
Route::Route(std::string location, std::string root, bool auto_index = true, bool cgi_enable = false)
{

	this->root = root;
	this->location = location;
	this->auto_index = true;
	this->cgi_enable = false;
```

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
> +};
Just du linting ;)
```suggestion
	methods.push_back("GET");
}
```

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
> +};
Par rapport au commentaire global!

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
>  };
Tu peux gagner beaucoup de place ici! Utilise les sets de valeurs!

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
>  };
Et pas besoin du ; à la fin!

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
> +{
Pense à checker si ton parametre n'est pas this! ça évitera de boucler ;)

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
> +Route::~Route(void){};
Pour uniformiser un peu le code !

```suggestion
Route::~Route(void)
{}
```

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
> +}
Dans cette fonction, tu devrai throw une erreur quand la methods n'est reconnu (GET, POST, DELETE, HEAD) !

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
> +	*/
Tout ça tu peux le supprimer, git le gardera en mémoire pour toi!

```suggestion
```

2022-05-31 21:00 UTC, restray commented on srcs/class/route.cpp
> +	std::cout << std::endl;
Pour pouvoir laisser les print dans le code sans avoir à se soucier des debugs!
```suggestion
	#ifdef DEBUG
	std::cout << "***Route***" << std::endl;

	std::cout << "Location : " << this->location << std::endl;

	std::cout << "root : " << this->root << std::endl;

	std::cout << "Methods : ";
	if (!this->methods.empty())
	{
		for (itp = this->methods.begin(); itp != this->methods.end(); itp++)
		{
			std::cout << *itp << " ";
		}
	}
	else
	{
		std::cout << "None";
	}
	std::cout << std::endl;

	std::cout << "Index : ";
	if (!this->index.empty())
	{
		for (iti = this->index.begin(); iti != this->index.end(); iti++)
		{
			std::cout << *iti << " ";
		}
	}
	else
	{
		std::cout << "None";
	}
	std::cout << std::endl;

	std::cout << "Error Pages : " << std::endl;
	if (!this->error_pages.empty())
	{
		for (ite = this->error_pages.begin(); ite != this->error_pages.end(); ite++)
		{
			std::cout << ite->first << " " << ite->second << std::endl;
		}
	}
	else
	{
		std::cout << "None";
	}
	std::cout << std::endl;
	#endif
```

2022-05-31 21:00 UTC, restray commented on srcs/class/route.hpp
> +#	define ROUTE_HPP
Si tu veux:

```suggestion
#pragma once
```

2022-05-31 21:00 UTC, restray commented on srcs/class/route.hpp
> +#endif
Et ducoup ici
```suggestion
```

2022-05-31 21:00 UTC, restray commented on srcs/class/webserv_conf.hpp
> +struct Webserv_conf
Pourquoi une struct et pas une class?
Concrètement une class est aussi pertinente!

2022-05-31 21:00 UTC, restray commented on srcs/class/webserv_conf.hpp
> +#	define WEBSERV_CONF_HPP
Ton rebase n'a pas correctement fonctionné... Tu as virer des modifications que j'avais faites auparavant!

2022-05-31 21:00 UTC, restray commented on srcs/class/webserv_conf.cpp
> +}*/
Tout ça tu peux le clean! Pas besoin de le garder dans le code

2022-05-31 21:00 UTC, restray commented on srcs/class/webserv_conf.cpp
> +Webserv_conf::Webserv_conf(std::string filename)
```suggestion
/**
 * @TODO Besoin d'une refracto de cette fonction! Séparation des différentes tâches.
 */
Webserv_conf::Webserv_conf(std::string filename)
```

2022-05-31 21:00 UTC, restray commented on srcs/class/webserv_conf.cpp
> +	while (i < 12)
Ca fonctionne! Mais ce n'est pas le mieux pour gérer cette partie!
Je te conseille d'utilise un vector plutôt!!

2022-05-31 21:00 UTC, restray commented on srcs/class/server_conf.hpp
> +# define SERVER_CONF_HPP
```suggestion
#pragma once
```

2022-05-31 21:00 UTC, restray commented on srcs/class/server_conf.hpp
> +#endif
```suggestion
```

2022-05-31 21:00 UTC, restray commented on srcs/class/server_conf.hpp
> +
```suggestion
```

2022-05-31 21:00 UTC, restray commented on srcs/class/server_conf.cpp
> +	std::cout << std::endl;
```suggestion
	#ifdef DEBUG
	std::list<short>::iterator itp;
	std::vector<std::string>::iterator iti;
	std::map<int, std::string>::iterator ite;
	unsigned int itr = 0;

	std::cout << "********Server********" << std::endl;

	std::cout << "Server name : " << this->server_name << std::endl;
	std::cout << "Body Max Size : " << this->body_max_size << std::endl;
	std::cout << "root : " << this->root << std::endl;

	if ((!this->port.empty()))
	{
		std::cout << "Ports : ";
		for (itp = this->port.begin(); itp != this->port.end(); itp++)
		{
			std::cout << *itp;
		}
		std::cout << std::endl;
	}

	std::cout << "Index : ";

	for (iti = this->index.begin(); iti != this->index.end(); iti++)
	{
		std::cout << *iti;
	}
	std::cout << std::endl;

	std::cout << "Error Pages : " << std::endl;
	for (ite = this->error_pages.begin(); ite != this->error_pages.end(); ite++)
	{
		std::cout << ite->first << " " << ite->second << std::endl;
	}
	std::cout << std::endl;

	std::cout << "Routes : ";
	std::cout << std::endl;
	while (itr < this->routes.size())
	{
		this->routes[itr].printRoute();
		itr++;
	}
	std::cout << std::endl;
	#endif
```

2022-05-31 21:00 UTC, restray commented on srcs/class/server_conf.cpp
> +	this->server_name = "webserv (42) v0.1-dev";
Essaye d'utiliser des DEFINE pour ça ! Histoire qu'on n'ai pas à le modifier partout dans le code!

2022-05-31 21:00 UTC, restray commented on srcs/class/server_conf.cpp
> +Server_conf::~Server_conf(void){};
```suggestion
Server_conf::~Server_conf(void)
{}
```

2022-05-31 21:00 UTC, restray commented on srcs/class/request.cpp
> +Request::~Request(void){};
```suggestion
Request::~Request(void)
{}
```

2022-05-31 21:00 UTC, restray commented on srcs/class/request.cpp
> +std::string Request::try_url(Response &res)
Peut-être documenter un peu cette fonction et son objectif! Je ne comprends pas son utilité

2022-05-31 21:00 UTC, restray commented on srcs/class/response.cpp
> +Response::Response( int client_socket, Webserv_conf &conf, Request const &req ) : conf(conf), req( req ) {
Du linting au passage!
```suggestion
Response::Response( int client_socket, Webserv_conf &conf, Request const &req ) : conf(conf), req( req )
{
```

2022-05-31 21:00 UTC, restray commented on srcs/class/response.hpp
> +class Request;
Ta class n'est pas déjà définie dans ton request.hpp ?

2022-05-31 21:00 UTC, restray commented on srcs/class/response.hpp
> +		const Webserv_conf &get_conf() const { return conf; };
Et ça il faudra le passer dans le fichier cpp! on pourrait avoir 0 bêtement...

2022-05-31 21:00 UTC, restray commented on srcs/class/server_conf.hpp
> +class Route;
Déjà défini dans le route.hpp non ?

```suggestion
```

2022-05-31 21:00 UTC, restray commented on srcs/http_header/Server.cpp
> +	//edited to use first server name
Ajouter une gestion de l'erreur dans le cas où il n'y a pas de serveurs dans ton array!

2022-05-31 21:00 UTC, restray commented on srcs/main.cpp
> +#include <stdio.h>
Il faut revoir le rebase! Le main n'est pas celui que j'ai édité

2022-06-01 08:17 UTC, restray commented on defaultPages/404.html
> +	<link rel="stylesheet" href="../404.css">
On n'est pas censé servir des données autres que les pages d'erreurs! Cette page est censé être build dans le cpp en fallback!

2022-06-01 11:23 UTC, Vatar commented on srcs/class/request.hpp
> +#	define REQUEST_HPP
Je suis d'accord pour passer tout les ifndef au pragma once, pour ma branche, je me suis tenu à modifier le code en-dehors de webserv_conf et server_conf le - possible.

2022-06-01 11:25 UTC, Vatar commented on srcs/class/request.hpp
> +#	define REQUEST_HPP
et absolument d'accord pour passer les attributs de Route en private et implémenter les getters nécessaires pour le code actuel

2022-06-01 11:41 UTC, Vatar commented on srcs/class/request.hpp
> +#	define REQUEST_HPP
C'est malheureux les ordinateurs à 42 ne peuvent pas auto-indent souvent...

2022-06-01 11:51 UTC, Vatar commented on srcs/class/request.hpp
> +#	define REQUEST_HPP
Je remplace par pragma once et je finis de coder tous les getters qu'on à besoin pour Route et je push

2022-06-01 11:58 UTC, Vatar commented on srcs/class/response.hpp
> +class Request;
On à plein de problèmes d'include circulaire, du coup le forward declaration d'un des commits du branch master "include fix" était ça

2022-06-01 12:02 UTC, Vatar commented on srcs/class/request.hpp
> +#	define REQUEST_HPP
c'est push'd

2022-06-01 12:08 UTC, Vatar commented on srcs/main.cpp
> +#include <stdio.h>
Étrange, j'ai fait et rebase et merge et c'est le même résultat

2022-06-01 13:55 UTC, restray commented
Tu as besoin de refaire une branche depuis master... certains des commits ne sont pas corrects :/

2022-06-01 13:55 UTC, closed without merging

2022-06-02 11:29 UTC, Vatar commented on srcs/class/response.hpp
> +		const Webserv_conf &get_conf() const { return conf; };
Oui, je corrige ça

2022-06-02 12:40 UTC, Vatar commented on srcs/class/request.cpp
> +std::string Request::try_url(Response &res)
Aucune idée, je n'ai pas fait Request

2022-06-02 15:37 UTC, restray reviewed
Ca m'a l'air niquel!